### ISSUE TITLE
🥊 🍱 Checkbox direction problem at AR.md file ✔️✅

### ISSUE THREAD

**Issue by BaseMax** [One-Language/One#149]

**Comment by BaseMax** [comment]
Please, one person, check and confirm it's solved or no. we need to know we have this problem or no.

**Comment by abdorah** [comment]
Are you talking about this problem:
![image](https://user-images.githubusercontent.com/37270435/127480706-9d922069-83a2-4cd0-922a-ded8adadf873.png)
this is a [screenshot from README_AR.md](https://github.com/One-Language/One/blob/master/README_AR.md)
The problem is when I open the file on my pc it works fine:
![image](https://user-images.githubusercontent.com/37270435/127481369-3d1bbcc4-f123-4c3b-a53c-d17fd4046105.png)
another part of the same document seems to work fine (because it is in English)
![image](https://user-images.githubusercontent.com/37270435/127481731-ba16e86f-2f28-4aa4-bc65-e8be148b6f95.png)

**Comment by mohitsaxenaknoldus** [comment]
I've found a fix to this: https://github.com/One-Language/One/pull/250
