### ISSUE TITLE
🏮 Add more information to the CONTRIBUTING guide 🏮

### ISSUE THREAD

**Issue by jbampton** [One-Language/One#173]
https://github.com/One-Language/One/blob/master/CONTRIBUTING.md

Good to have more on:

- Tips on pre-commit
- Python
- yamllint
- markdownlint
- Clang Format
- Git hooks
- Homebrew
- Windows 10 setups
- Ubuntu WSL
- Oracle VirtualBox
- Ubuntu

**Comment by abdorah** [comment]
Hi @jbampton , This is a good idea since it would be more helpful for newcomers to have a good guide on how to help. I am working on this right now but can you give more details about this:

> Good to have more on:
> 
> * Python 
> * Clang Format
> * Git hooks
> * Homebrew
> * Windows 10 setups
> * Ubuntu WSL
> * Oracle VirtualBox
> * Ubuntu

I tried to make something like this:

<h1 align="center"><strong>Contributing to the ONE Programming Language</strong></h1>

> Welcome new contributers! First of qll thank you for contributing!
> :+1: :tada: 

## How to Contribute

#### **First, Discuss**

`The ONE Programming Language` is a very welcoming community. We appreciate your ideas and your help. You need to communicate in [our discord server](https://discord.com/invite/sFCE2HcMCa) or pick an issue and share your perception of the solution you have. Don't forget to fork this repository and to work on your contribution.

### **Then, make a PR**

Now that you finished the work, don't forget again to run pre-commit. Create the pull request and use the description to provide context and motivation, as you did in the issue. Otherwise, you can mention your PR in the issue that you tried to solve. Once a pull request is created, we will verify the code and accept your PR.


## Contribution Tools

### Pre-commit
A framework for managing and maintaining multi-language `pre-commit` hooks.
Pre-commit can be [installed](https://pre-commit.com/#installation) with
`pip`, `curl`, `brew` or `conda`.

You need to first install `pre-commit` and then install the `pre-commit` hooks
with `pre-commit install`. Now `pre-commit` will run automatically on git
commit!

If you have [Python](https://www.python.org/) at your system, so you can
easily install pre-commit via `pip install pre-commit`.

It's usually a good idea to run the hooks against all the files when
adding new hooks (usually `pre-commit` will only run on the changed files
during git hooks). Use `pre-commit run --all-files` to check all files.

To run a single hook use `pre-commit run --all-files <hook_id>`

To update use `pre-commit autoupdate`

- [Quick start](https://pre-commit.com/#quick-start)
- [Usage](https://pre-commit.com/#usage)
- [pre-commit-autoupdate](https://pre-commit.com/#pre-commit-autoupdate)

### Python

### yamllint

### markdownlint

### Clang Format

### Git hooks

### Homebrew

### Windows 10 setups

### Ubuntu WSL

### Oracle VirtualBox

### Ubuntu

### Docker image

## Contribution Rules

My reference is: [spring contribution](https://github.com/spring-projects/spring-framework/blob/main/CONTRIBUTING.md)

**Comment by BaseMax** [comment]
If you get a chance, complete this and send a PR. After that, we can close this issue and keep you updated content in **CONTRIBUTING** file.

**Comment by jbampton** [comment]
Done well enough for now.  Thanks everyone !!
