### ISSUE TITLE
Ignore the `src/parser/parser` binary file in gitignore

### ISSUE THREAD

**Issue by BaseMax** [One-Language/One#203]
Hi there,

We have to ignore the `src/parser/parser` binary file in gitignore.

This is what git status i see while I'm developing:

```
[max@workstation One]$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   src/input.one
	modified:   src/parser/parser
	modified:   src/parser/parser.c

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by BaseMax** [comment]
I already added this to the **.gitignore** file but it seems not to work.

https://github.com/One-Language/One/blob/master/.gitignore#L9

**Comment by BaseMax** [comment]
I think already been solved, Just we need to test it with another person, not me.

Let me know results, after that we can close this issue. :heart:

**Comment by abdorah** [comment]
Hey, @BaseMax I see that you already solved this problem. I think that the `.gitignore` file that you added works perfectly.
This is a picture of the actual `.gitignore` file that you wrote:
![image](https://user-images.githubusercontent.com/37270435/127392881-824c6cf6-05c3-470c-b5aa-91480ff2d0b1.png)
And this is working in my case because as you can see git "ignores" `parser`
![Screenshot from 2021-07-28 21-44-28](https://user-images.githubusercontent.com/37270435/127393412-1ba99205-bc81-452c-9838-e1ff8a8c355c.png)

**Comment by BaseMax** [comment]
Thank you, so this work.
